name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: true
      matrix:
        php: ["5.3", "5.4", "5.5", "5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1"]

    name: PHP ${{ matrix.php }}/Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install PEAR
        if: matrix.php < 7.4
        run: |
            sudo apt-get update
            sudo apt-get install php-pear
            pear version

      - name: Execute tests
        run: pear run-tests tests/*.phpt

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Diffs
          path: tests/*.diff
